ALTER TABLE students
  ADD COLUMN father_name VARCHAR(100) NULL,
  ADD COLUMN father_phone VARCHAR(20) NULL,
  ADD COLUMN father_email VARCHAR(100) NULL,
  ADD COLUMN mother_name VARCHAR(100) NULL,
  ADD COLUMN mother_phone VARCHAR(20) NULL,
  ADD COLUMN mother_email VARCHAR(100) NULL,
  ADD COLUMN address_line1 VARCHAR(255) NULL,
  ADD COLUMN address_line2 VARCHAR(255) NULL,
  ADD COLUMN city VARCHAR(100) NULL,
  ADD COLUMN state VARCHAR(100) NULL,
  ADD COLUMN postal_code VARCHAR(20) NULL,
  ADD COLUMN country VARCHAR(100) NULL;

