CREATE TABLE IF NOT EXISTS students (
  id BIGINT AUTO_INCREMENT PRIMARY KEY,

  class VARCHAR(50) NOT NULL,
  section VARCHAR(50) NOT NULL,
  room VARCHAR(50) NOT NULL,
  status ENUM('active', 'inactive') DEFAULT 'active',
  std_limit INT NOT NULL,

  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

